language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: Bqi77kjZXPMefCy1SZEhWd/IxXufXmJ/jVeUfJwbNAKJoxZQ6KBnRcFPMLapGLAaxIFsqkxUrL54PDfnzc8/zSYfEPPNAXXEO2eGgasTviBa2rZyLxH8cvXsurr/NJse9gZyisZBrMnUp2P/nBmNfyAk3V/E895CxLFhfQsXsLSJZSxZp6UT4FxJF9HrikvSTrkZfHL3hNLjj9noJOYa0gG6rgFOp3LMXGyunV77bcG7o6xQDU+tBrNqCN+Muj1PRx/XzHBWZ4fvOJ4f0tI6UARIID6wEvWEr8jWp4PkQ2hhdTVRhIZWwkTr5HAPqUssyLWncXVSC0EWU/03lwI3wHdckW97f46fsGFpoOTjb4S0pECokHj+h55PWxH5DexvoQXMuRr+8+l8cQIR6yyT6SMoWcvCIHXL3DlYo7IfvODIfcxeGVgdazviht95U1onb0CT8bjOhnDT4OpZUwee5rTeEFbQ9TqJtkgN9OBYRs+mzgcc4Cc/WpjzcqNKfMlLSRLf2MKuIlLsfC77fxah1MF9EeHLl3EDRWHOzr8vd56YmfqLi00WvREyP5X0tv0yIHrJP/BwHes67hWZSH9rvuMdPoCdOUOUP0adAbGuI8K/6xNSL6eMbA0pMi8g3auIL8ZRnIIhf5oaeNNzpF+yDwYjIkgMjEfnrUWQbpTFgzE=
  app: tim-noteful-v4
  on:
    repo: thinkful-ei19/tim-noteful-v4
