language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: nXPRI3ufez/SNDYvEEcsXDd5lT6q4Y5c2n/aIwO16n3YUwBd2yw2HMLXTp1w2QnXkZGlcO+ZFWrZJqS3Rug3TxGv+u5zo4z7iVyGRT1sHGDTWUK08z4TMu9LED0DOZkr/pZpSp+vPbWUJL1TeFZMS+W85refV21noQ735hs9++foeIzmE/5n80bGD0D6ulvl1wzb9L3tMJmjF/WfcyCxSB9nWGS9hnoXFoL8/WvVxcvuoYiYYrEWvci69Rbx58XIbwqnZ/6RfNL2mljiXKO9rEiV6dxUqAwc8+4m/ksFOQXPjYiu3ZYYMoVXvTnj5eSycDHQPvWfYDe9UIUqA4xBjZWtJJcg/i8qgrJ99R/KyUuW9u7d2we+FvvMP7xcGm79lmluJXj2TsptqxxuAC/A9PEu9Z8kThDTV5bXRXTUazrOAtIQKT9hHltohJnIehhp+4SRIDYN4pJPnOIdeynsoBNNykbdPkCivCEngvw2yB2UtpXSGfsl8jVYkFp8AD4I2a/dD+H1UpNQbrCoNB07GiZ8L4I+K96sQFsGGTcpgva5MCbdwvd6EgUPSy4unlJPaEJltdwr4PZMUXLDAIkNo8XnHyydwDaOluvQGLrn08xDkDcGetVcMGO3mTw/42zUqPfwuvFaaIySXXlRevKvtjCamMKHMgdpZwPqvEYsUtE=
  app: tim-noteful-v4
  on:
    repo: thinkful-ei19/tim-noteful-v4
