language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: eJpvsKfFxP555wIBL/Bqz8XmxOidwgu5DMVIVTL9Q0jG2gubEJOUApZoYnx0aqt3db2csU/8NzUTQGd8UieultvIamoxSmJcdCamLgPp+QMYSAg7Bp+2sc12AbL7C1ght6eqM0KxoL8cNXWZ+9HtHL9ruYLCP4snXJb3NI4HSjlrri9vCxrJ4Efg9ahCsSFNZhTwxqLeJAyhkRocfVuurPZZtY1bFg9hbUDGbcjqCfX7KLiXISplMGwVoOwHXC8U202LbuwzH7kq8CFld7Cfb13m31uuOiFPKArbAgN5BAL9ntOlz73EhrTlKkq7dV/2tW4K9bpks8xp1C271MOE2I3az1MO4msbo+eBb2xdCEhoC5LDTD+ow73lmxVUPzBXI/Zdjrn9DNlmwioDgmbTmt5u4cAbCfl+8hNGtBYBVisadoKRv4Ev6qA/ZfoazVUxu2L51vmQX0NZRIPBPjX4XZRLtWETvzVlt7L4QHUbwm689RPNfn/p/vCvqd0V9pOKt3au+OLO6H5ihX2RxQzDyXdJxr7jCyJYPGEajSSYSTBeV9XF9s8wVObbECtd+qOz7clPZqwwE9jQ580p6aPmyc7pd8XqffmD/XHsY08lkeF0RAdFfDfK4RCZyC5a5L3X+xmC+mw/cPR45GguW2cOnAh6pBnRHHLxN1a+X3FKG3U=
  app: notefulappv4-tim
  on:
    repo: thinkful-ei19/tim-noteful-v4
