language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: NneDhtb41pu2wPZUkA1ttcO2JFErl0KA90WEwwQUMuepjg/F3hAY+5JV236/wPAjJtGHS2karcw8GauGw0z1jgcMnVV6y17N0/uQMmdpSxbf1ATVe1wD68pxAkBZh7OFlOXunpFnoHOt3gjCUutP94X+EsAmPrxDqsYFD09FC1JLSU+18+fZmCVtPGhLefpb0Nkux6sw9hH4BPu1AwOJvQkZsS7EaMN1ZpEeV5Jwa1RrN8ccR5b4oAJt4jAk9eH98soXtunph5Rpd09yA3A+46BAoH25xzSpWEXuI2ifGxaJ2qYuIkNFcnPFtbP46cnKc1mpIUZjZwlPAhXUNvTY6XcWgZHLdnPAdaIkUOcASy81FKWpeHA6FubJOxtnRIR2BBHZMq+bbrgE7ymY7zZXBIbntJeZm8d2tT+QPWi1PXDR0DePTAtIS6bZv11Dqbv+tMV5X378Afe08CBp+g78RWXkabJwoRQxvnI5+3vhE8VJi3lWakHfKlyZeXgrSNlOBSqg4bX/tCyNZqRmBM8xrG+/hXKYnn7w+8D5adRi0Mljxy3/7p6cHm1jcROGfkDjmskRwClX+WuGm1WUTHZMJIxcpVpo3AY+Q7zq296f3ldvGx0k6pokfrcn1t6UQxjLT2inVLRV4dNHB7u6BViz9HBl0/qs4kTfqCK9ccNuprA=
  app: tim-noteful-v4
  on:
    repo: thinkful-ei19/tim-noteful-v4
